spring.datasource.url=jdbc:mysql://mysql:3306/bd_ventas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
producto.service.url=http://producto:8084/api/productos
usuario.service.url=http://gestionusuario:8081/api/usuarios
estado.service.url=http://estado:8083/api/estados
bodega.service.url=http://gest-bode:8085/api/productos_ubicaciones
